microsoft/vscode-hexeditor

media/chunkHandler.ts
media/eventHandlers.ts
media/hexEdit.ts
media/messageHandler.ts
media/virtualDocument.ts
package.json
src/hexEditorProvider.ts

Make scroll feel smoother by
1. Appending in large chunks rather than one element at a time
2. Reduce the number of event listeners
3. Improved message passing between the extension host and the webview
4. Remove debounce on scroll.

Scroll optimizations

---

package-lock.json
package.json
src/extension.ts
src/hexDocument.ts
src/hexEditorProvider.ts

Adds telemetry so that we can see what size files users are opening to give us a better idea of how much time to initially commit to things such as large file optimizations.

Add fileSize telemetry

---

README.md

Fix typo in version number

---

media/dataInspector.ts

Takes @StefanoCecere's suggestion and resolves #14.

Remove invalid from the wording in data inspector

---

dist/hexEdit.css

Attempt to fix https://github.com/microsoft/vscode-hexeditor/issues/24 in most cases. Some themes it helps better than others, might need to come up with new colors.

Use a better color for the surrounding focus of an element

---

dist/hexEdit.css
media/chunkHandler.ts
media/editHandler.ts
media/eventHandlers.ts
media/hexEdit.ts
media/messageHandler.ts
media/srollBarHandler.ts
media/util.ts
media/virtualDocument.ts
package-lock.json
package.json
src/hexDocument.ts
src/hexEditorProvider.ts

This adds basic undo, redo, edit, and save support to the hex editor. Fixes #17. 
I'm sure there will be more advanced editing requests and I'm open to any feedback on how to make the editing experience better so feel free to open more issues :).  
Here's a gif of what editing looks like, once it is tested this will makes it way into the next release!

Simple editing

---

media/chunkHandler.ts
src/hexEditorProvider.ts

Fixes #18. Empty files will just have a singular plus cell so you can type into them.

Fixes empty files not rendering correctly

---

.vscode/launch.json
dist/hexEdit.css
media/editHandler.ts
media/eventHandlers.ts
media/hexEdit.ts
media/selectHandler.ts
media/util.ts
media/virtualDocument.ts
media/webviewStateManager.ts
package-lock.json
package.json
src/hexDocument.ts
src/hexEditorProvider.ts
tsconfig.backend.json
tsconfig.json
tsconfig.webpack.json

Adds support for copy and pasting. Also allows you select multiple items by holding down ctrl and clicking multiple cells.
Update:
Shift click support
Click and drag support #7

Copy, Paste, and Multi Select Support

---

media/chunkHandler.ts
media/editHandler.ts
media/hexEdit.ts
media/virtualDocument.ts
media/webviewStateManager.ts
src/hexDocument.ts
src/hexEditorProvider.ts

Adds support for the revert file command and basic file watching. Fixes #79, #74, #64, #62, and #55

File Watching + Revert

---

dist/hexEdit.css
media/chunkHandler.ts
media/editHandler.ts
media/eventHandlers.ts
media/searchHandler.ts
media/selectHandler.ts
media/srollBarHandler.ts
media/util.ts
media/virtualDocument.ts
media/webviewStateManager.ts
package-lock.json
package.json
src/hexDocument.ts
src/hexEditorProvider.ts
src/searchProvider.ts
src/searchRequest.ts

This PR got a bit out of hand. 
This PR contains search support, find and replace support, and copy and paste improvements. This also fixes #95 which allows all selections to be preserved upon switching tabs
There's still a few styling fixes I want to make, but the general functionality is there.

Find + Replace + Improved Copy and Paste

---

src/fileSystemAdaptor.ts
src/hexDocument.ts

Fixes #52. This is the initial code necessary to support untitled files, an upstream issue is being tracked at https://github.com/microsoft/vscode/issues/114711 to offer better support without the need for this strange workaround.

Support for untitled files 

---

.editorconfig
dist/hexEdit.css
dist/inspector.css
media/data_inspector/byteData.ts
media/data_inspector/dataInspector.ts
media/data_inspector/inspector.ts
media/editor/byteData.ts
media/editor/chunkHandler.ts
media/editor/dataInspectorHandler.ts
media/editor/editHandler.ts
media/editor/eventHandlers.ts
media/editor/hexEdit.ts
media/editor/messageHandler.ts
media/editor/searchHandler.ts
media/editor/selectHandler.ts
media/editor/srollBarHandler.ts
media/editor/util.ts
media/editor/virtualDocument.ts
media/editor/webviewStateManager.ts
src/dataInspectorView.ts
src/extension.ts
src/fileSystemAdaptor.ts
src/hexDocument.ts
src/hexEditorProvider.ts
src/searchProvider.ts
src/searchRequest.ts

The indentation was a bit all over the place, this brings in an .editorconfig file (same as in microsoft/vscode) and formats all ts/css files.

Add editorconfig from vscode and format

---

.eslintrc.json
src/dataInspectorView.ts
src/hexDocument.ts
src/hexEditorProvider.ts
src/test/runTest.ts

Fix eslint warnings

---

dist/inspector.css

Improve data inspector grid space usage

---

README.md
package.json
src/dataInspectorView.ts
src/hexEditorProvider.ts

Fixes #223
I'm pretty happy with the webview data inspector after this new setting and pulling it into the explorer, so I added a section in the readme for how to do that.

Add new auto reveal setting with docs

---

media/editor/virtualDocument.ts
src/hexEditorProvider.ts

Fix first column widget across font size/zoom

---

.esbuild.config.js
media/editor/dataDisplay.tsx
media/editor/findWidget.tsx
media/editor/hooks.ts
media/editor/scrollContainer.tsx
media/editor/state.ts
media/editor/virtualScrollContainer.tsx
shared/fileAccessor.ts
shared/hexDocumentModel.ts
shared/util/once.ts
src/fileSystemAdaptor.ts
src/hexDocument.ts
src/hexEditorProvider.ts

From the TPI issue. I also added support for native file reading to support large files. Each commit is self-contained, I recommend reviewing them individually.
Fixes #322, #321, #320, #313, and #319

Streaming 1 fixes

---

media/data_inspector/byteData.ts

Making explicit endian indexing of the adjacent bytes and explicit signed conversion.

Fixing 24-bit view #330

---

media/editor/dataDisplay.tsx
media/editor/state.ts

fix: data inspector overlap

---

.github/workflows/pr-chat.yml

Add pr-chat.yml so it uses the code review chat action

Onboard to codereview bot

---

media/editor/dataDisplayContext.tsx

Fix #375
Don't utilize native selection when a custom option is available

Ignore native selection where we have a custom selection

---

CHANGELOG.md
package-lock.json
package.json

Bump the package version to release new version

Bump version for release

---

.esbuild.config.js
.vscode/launch.json
media/editor/state.ts
package-lock.json
package.json

Fixes https://github.com/microsoft/vscode-hexeditor/issues/374 -- with a brief diversion to find an esbuild bug 😱

update linaria, make webview sourcemaps work

---

media/editor/vscodeUi.tsx

Shrink thickness of progress bar

---

.esbuild.config.js
package-lock.json
package.json

Seems to give us marginally better performance, too.

chore: update react and recoil

---

media/editor/scrollContainer.tsx
media/editor/state.ts
shared/protocol.ts
src/hexEditorProvider.ts

fix: respect editor.scrollBeyondLastLine

---

media/editor/dataDisplayContext.tsx
media/editor/dataInspector.tsx
shared/protocol.ts
src/extension.ts
src/hexEditorProvider.ts
src/statusSelectionCount.ts

add functions to count selected bytes

---

src/hexEditorRegistry.ts

Fix: the selection count is updated when switching between tab groups.

---

media/editor/dataInspectorProperties.tsx

Ref #418.
To keep the function private I didn't add a test file for `getFloat16`, but I did write one here https://github.com/lorsanta/float16.
Let me know if it needs to be added.

Add fp16 and bf16 support in data inspector

---

src/hexEditorProvider.ts

fix: dispose all disposables in openCustomDocument

---

media/editor/dataDisplay.tsx
media/editor/dataInspector.tsx

- Avoid selecting 1 byte past the end of the file
- Fix mouse-selecting from the first byte not working
Closes #455

fix: slight selection bugs

---

package.json

Fixes https://github.com/microsoft/vscode-hexeditor/pull/478#issuecomment-1923361250

Fix plugin description

---

media/editor/dataInspectorProperties.tsx

Display the ascii character of the current byte in data inspector

Display ascii character in data inspector

---

src/statusSelectionCount.ts

Show status offset and selection count in decimal and hexadecimal as '0d.../0x...'

Show status offset and selection in dec and hexa

---

package-lock.json
package.json

Bump version to release new fixes for verifications

Bump version to release new fixes

---

build/pipeline.yml

This pipeline cannot run in CI so we must disable it.
We should explore a separate CI pipeline

Add pr none to 1es

---

.github/workflows/pr.yml

Adds a github action for PRs to be validated, compiled, and tested

Add a PR github action

---

package.json

Removes duplicate webview/context to silence "duplicate webview/context" warning.

fix: removes duplicate webview/context

---

media/editor/dataInspectorProperties.tsx

fix: correctly show big-endian utf-16 chars

---

media/editor/state.ts

Fix: DisplayContextSelection read violation (#547)
