microsoft/vscode-hexeditor

README.md
package-lock.json
package.json
src/extension.ts

This updates the README and adds an explicit command to the command palette which allows for opening the file in the hex editor. This command also shows up if you type the word hex. 
This is to address the issues regarding discoverability as outlined in
https://github.com/microsoft/vscode-hexeditor/issues/32 and 
https://github.com/microsoft/vscode-hexeditor/issues/34

Add open with hex editor command

---

dist/hexEdit.css

Fix #24. This squares off the text in the editor (wasn't able to fully square the decoded text due to spans not being able to be given a width). This also adds an offset to make the focus pop a bit more per @misolori's suggestion.

Better focus

---

dist/hexEdit.css

Improves upon #23. Brings the contrast ratio up to 6.45 and removes the border unless in high contrast theme. The gutter is a bit more difficult because the colors mimic that of VS Code and any changes I make seem to make it a bit uglier.

Adds better contrast to the header

---

media/byteData.ts
media/dataInspector.ts
media/util.ts

Resolves some of the issues outlined in #84. This doesn't handle grapheme clusters and only support single codepoints (So any unicode character that can be represented in 4 bytes).

Better utf-8 and utf-16 parsing

---

media/editHandler.ts
media/searchHandler.ts
media/selectHandler.ts
media/util.ts
media/virtualDocument.ts

Improves the selection while dragging with the mouse, <kbd>shift</kbd> + click , <kbd>shift</kbd> + <kbd>home</kbd>, <kbd>shift</kbd> + <kbd>end</kbd>.
Took as reference the [HxD editor](https://mh-nexus.de/en/hxd/)
Fixes #78

Improve cell selection

---

media/editHandler.ts
media/eventHandlers.ts
media/util.ts
media/virtualDocument.ts

Switch from using attributes to represent the offset of a cell to classes for faster querying of the DOM.

Switch from attributes to classes

---

media/hexEdit.ts
media/virtualDocument.ts
package-lock.json
package.json
src/hexDocument.ts
src/hexEditorProvider.ts

I apologize if I didn't do things right. Even tabs vs. spaces. I am not a TypeScript expert either. Please review and I will do whatever is needed.
Basically, even if you are reading a file, the base address is not always zero. This is an awesome extension and I want to use it in a debugger. I am trying to address Issue #70 that I filed. It is only one part of the solution.
**Bottom line: adds an offset to the addresses displayed**
Yes, I have some imports for `fs` as I was using them for debugging and logging. As I found out, debugging two extensions at the same time was a bit challenging.
Btw, `npm install` fails for me because I don't have the `nan` package installed globally. I can fix `package.json` if you want.

Allow a base address to be added to a file via a URI

---

package.json

This PR fixes #184.
This way it better appears on command palette.

Renamed command from HexEditor to Hex Editor

---

media/editor/hexEdit.ts
media/editor/virtualDocument.ts
package.json
src/extension.ts
src/hexEditorProvider.ts
src/util.ts

Adds a command accessible from the command palette that allows a user to go to a specific cell / line offset. This addresses common requests such as #191 and #83. Sadly, it doesn't appear that you can override the `CTRL + G` keybinding and therefore it is only accessible from the command palette at this time.
Resolves #191 and #83.

Add the ability to go to a certain file offset

---

dist/hexEdit.css
media/editor/searchHandler.ts
media/editor/selectHandler.ts
media/editor/srollBarHandler.ts
media/editor/virtualDocument.ts
media/editor/webviewStateManager.ts
src/hexEditorProvider.ts

Makes the search widget follow similar behavior to the text editor in VS Code. This is a better and more at home solution than #201. @tigerbeard We will need to figure out what to do with your search results page as it won't feel like a native experience in a pull down widget such as the one you see in VS Code's text editor. Maybe following something similar to #199 would be best for that.

Editor Search Widget

---

README.md

This is just something that can suffer from bitrot, if it was important the
marketplace and/or extension sidebar could mention the required version.

Don't mention engine version in readme

---

src/fileSystemAdaptor.ts

Now `vscode.workspace.fs` can use interface exposed by other contributed file system providers. After removing scheme check in `fileSystemAdaptor.ts`, Hex Editor extension is able to edit files provided by other extensions' file system provider (related issue: https://github.com/fython/vscode-gwo-android-helper/issues/1).

Support different scheme file uris

---

media/data_inspector/byteData.ts

A check was setting 0 and null to NaN instead of just null
Fixes #232
Fixes #222

Fix inspector sometimes saying end of file

---

CODE_OF_CONDUCT.md
README.md
package.json

Changes/justification:
- Removed header from top of readme as it re-states the title when viewing the
extension in marketplace/vscode
- Moved code of conduct to CODE_OF_CONDUCT.md, it's not relevant to people using
the extension
- Various wording improvements, made some sections more concise and removed
details that weren't important (eg. navigating/scrolling support)
- Moved easiest how to use steps to the top of the list
- Removed the contributed settings section as it repeats the contribution tab
within vscode
Fixes #221

Tidy up readme/ext description

---

dist/inspector.css

Fixes #130
This makes the inspector stable for almost all characters, I couldn't figure out how to deal with `ᬮ` in particular without resorting to `position:absolute` which feels hacky and not worth it.

Keep utf-16 stable for most characters

---

dist/inspector.css
package.json
src/dataInspectorView.ts

Part of #132
Part of #223
What it looks like now:
Pulled into explorer:

Remove data inspector header, improve panel name

---

media/editor/editHandler.ts

Fixes #280 
Fixes #281
Typing '.' or '+' in places mentioned in those issues is going to work now.
Both issues emerged from the same code.

Fixes the unability to type dot or plus in some places

---

media/editor/selectHandler.ts
media/editor/virtualDocument.ts

Fix Shift+Click selection

---

package.json

You can't use the default Goto line command in the HexEditor. You get the message "Open a text editor first to go to a line."
Therefore I suggest overriding the default Goto keybinding while in the HexEditor with the gotoOffset command to get some utility back.
This also closes issue #212.

Add keybinding for gotoOffset

---

.vscode/settings.json
media/editor/copyPaste.tsx
media/editor/dataDisplay.tsx
media/editor/hooks.ts
media/editor/state.ts
media/editor/vscodeUi.tsx
shared/protocol.ts
src/fileSystemAdaptor.ts
src/hexDocument.ts
src/hexEditorProvider.ts
src/util.ts

Quick version of copy/paste. Pasting brings up the following dialog:
Copying will copy the base64 version if the binary side is selected, or the utf-8 version of the text if the text side is selected.
Also, there were some changes in the `fileSystemAdaptor.ts`. I realized that inserting certain text could lead to an infinite loop (and infinite size) when writing a file, since instructions to read content from the file could read newly written text and cause it to keep duplicating. To fix this, I modified the native filesystem adapter so that (if a file needs to be written, i.e. if there was a length change) it writes to a temp file and is renamed. As referenced in the comment, this should have minimal performance impact. I realized this also fixes an issue where files couldn't be shrunk …

feat: add copy/paste back in

---

README.md

editorAssociations configuration has changed in current versions of VSCode and is now being reflected in the README

Update README to reflect current configuration

---

CHANGELOG.md
package-lock.json
package.json

- Updates changelog to include previously missed versions
- Updates package.json for 1.9.8 release

Update changelog and version for release

---

media/editor/dataInspectorProperties.tsx

This adds the binary representation of the selected value to the data inspector properties. This property is especially useful for analyzing bit fields and non-standard types. Here's a screenshot of what it looks like:

feat: add binary type to data inspector properties

---

CONTRIBUTING.md
README.md

While contributing, I noticed some outdated documentation:
- yarn is no longer used.
- esbuild is now used instead of webpack.
- The data inspector has three different setups with `aside` being the new default.

docs: fix inconsistencies in README and CONTRIBUTING

---

media/editor/state.ts
shared/fileAccessor.ts
shared/hexDocumentModel.ts
shared/protocol.ts
src/fileSystemAdaptor.ts
src/hexDocument.ts
src/hexEditorProvider.ts

Effectively resolves https://github.com/microsoft/debug-adapter-protocol/issues/322
It seems the default of 128KB is too much for many embedded DA's to be able
to serve in a satisfactory way.
Also, it seems that paging debug data wasn't working before. Whoops.
Fixed that as well.

fix: use a smaller page size for debug memory

---

media/editor/scrollContainer.tsx

There were a couple issues around scroll, this makes it feel more native: we only actually scroll to full rows, but if there's unused scroll delta that doesn't get us all the way to the next row, use that in the next event.

fix: accumulate scroll delta for better trackpad scrolling

---

media/editor/state.ts
shared/protocol.ts
src/hexEditorProvider.ts

Fixes #119
Mostly making multiple things being able to listen to renderer events.

fix: update scroll size when underlying file size changes

---

media/editor/dataDisplay.tsx
media/editor/state.ts

Some small weekend tweaks.
This moves data retrieval from data rows into data pages. I noticed a bunch of time was spent negotiating data retrieval inside each `<DataRowContents />`, so this improves that by making it happen in one (or, if the user is on a boundary, two) places instead of 30+. This net about a 30% boost over the original 'new page' render time.
I also moved the DOM structure to be based on DataPages that are in layers and moved as a group instead of inidivudally. This net an additional 15% improvement over the original 'new page' time.
Cost to render a new page before:
after:

refactor: get a 45% performance boost

---

media/editor/dataInspectorProperties.tsx

Realised I could add this myself re: #405

Add octal representation of the current byte in data inspector

---

package.json

Now that VS Code implicitly registers many activation events, we don't need these

Remove implicit activation events

---

.esbuild.config.js
.vscode/settings.json
media/editor/copyPaste.css
media/editor/copyPaste.tsx
media/editor/css.d.ts
media/editor/dataDisplay.css
media/editor/dataDisplay.tsx
media/editor/dataDisplayContext.css
media/editor/dataDisplayContext.tsx
media/editor/dataInspector.css
media/editor/dataInspector.tsx
media/editor/findWidget.css
media/editor/findWidget.tsx
media/editor/hexEdit.css
media/editor/hexEdit.tsx
media/editor/scrollContainer.css
media/editor/scrollContainer.tsx
media/editor/settings.css
media/editor/settings.tsx
media/editor/util.css
media/editor/util.ts
media/editor/virtualScrollContainer.css
media/editor/virtualScrollContainer.tsx
media/editor/vscodeUi.css
media/editor/vscodeUi.tsx
package-lock.json
package.json

Fixes https://github.com/microsoft/vscode-hexeditor/issues/413

debt: remove dependency on linaria, use css modules instead

---

src/fileSystemAdaptor.ts

Possible fix for the editor failing to open read-only files (https://github.com/microsoft/vscode-hexeditor/issues/422). I added everything per https://github.com/microsoft/vscode-hexeditor/issues/422#issuecomment-1561828617.
Please let me know if there are any issues or questions.
(Note: Same PR as https://github.com/microsoft/vscode-hexeditor/pull/435. I needed to change accounts. Sorry for any inconvenience)

Fixed editor failing to open read-only files

---

media/editor/dataDisplay.tsx

Fix #425. The issue was due to the fact that `onDidChangeAnyFocus` returned immediately if the focused byte was 0.

fix: scroll to the top when hit home key

---

media/editor/dataDisplayContext.tsx
package.json
shared/protocol.ts
src/extension.ts
src/hexDocument.ts
src/selectBetweenOffsets.ts
src/selectUntilOffset.ts

Implements a simple command that enables user to select byte values between 2 offsets.
Useful for extracting embedded files. 
closes #469

Select between offsets

---

media/editor/dataDisplay.tsx
media/editor/dataDisplayContext.tsx
media/editor/findWidget.tsx
media/editor/scrollContainer.tsx
media/editor/state.ts
media/editor/util.ts
package-lock.json
package.json
shared/protocol.ts
shared/util/range.ts
src/hexEditorProvider.ts
src/test/index.ts
src/test/range.test.ts

It was a long time on my todo to fix the "publishSelections", as it was
previously linear time with the _number of bytes_ selected -- not the best.
Once I fixed that, supporting deletions was fairly trivial, although it
is handled a little differently than other edits...
Closes #466

fix: improve range selection logic, support delete

---

build/pipeline.yml
media/editor/copyPaste.tsx
media/editor/dataDisplay.tsx
media/editor/dataInspector.tsx
media/editor/findWidget.tsx
media/editor/hexEdit.tsx
media/editor/readonlyWarning.tsx
media/editor/settings.tsx
media/editor/strings.ts
package.json
package.nls.json
shared/strings.ts
src/dataInspectorView.ts
src/goToOffset.ts
src/hexEditorProvider.ts
src/selectBetweenOffsets.ts
src/statusSelectionCount.ts
src/util.ts

chore: localize the extension

---

.vscode/launch.json
media/editor/findWidget.tsx
media/editor/state.ts
package-lock.json
package.json
shared/protocol.ts
src/fileSystemAdaptor.ts
src/hexEditorProvider.ts
src/searchRequest.ts
src/test/range.test.ts

Assorted fixes

---

media/editor/dataInspectorProperties.tsx

Closes https://github.com/microsoft/vscode-hexeditor/issues/464.

add common cjk encoding (gb18030 for simple Chinese, big5 for traditional Chinese, euc-kr for Korean, euc-jp for Japanese) datatype support

---

media/editor/dataInspectorProperties.tsx

Keep the unsigned format before the signed format, to be consistent with all other formats

Display unsigned before signed int64

---

media/editor/dataInspectorProperties.tsx

Show in data inspector missing large integer formats as ULEB128 and SLEB128 (Little Endian Base 128)
Closes #485

Display in data inspector ULEB128 and SLEB128

---

media/editor/hexEdit.css
media/editor/hexEdit.tsx

Instead of using the default font-size, uses the editor's font-size.
Closes #504

Fixes wrong font-size var

---

media/editor/dataDisplay.tsx
media/editor/dataDisplayContext.tsx
media/editor/state.ts
shared/hexDocumentModel.ts
src/fileSystemAdaptor.ts
src/hexDocument.ts
src/searchRequest.ts
src/test/hexDocumentModel.test.ts
src/test/searchRequest.test.ts

Should fix #511. Took me a bit of time to figure out everything, but I think the solution is working. I also added some tests to triple check the work.

Fix: duplicate saving and stale webview.

---

CHANGELOG.md

When checking the release, I noticed that the CHANGELOG entries are incorrect

Fix swapped entries

---

media/editor/dataDisplay.tsx
package.json
package.nls.json
src/extension.ts

Ref #519
Both commands copy the focused element's offset.

Add copyOffsetAsHex/Dec

---

.esbuild.config.js
media/editor/dataDisplay.tsx
media/editor/state.ts
media/editor/util.css
media/editor/util.ts
package-lock.json
package.json
package.nls.json
shared/decorators.ts
shared/diffWorker.ts
shared/diffWorkerProtocol.ts
shared/hexDiffModel.ts
shared/hexDocumentModel.ts
shared/protocol.ts
shared/util/myers.ts
shared/util/uri.ts
src/compareSelected.ts
src/extension.ts
src/fileSystemAdaptor.ts
src/hexDiffFS.ts
src/hexDocument.ts
src/hexEditorProvider.ts
src/hexEditorRegistry.ts
src/initWorker.ts

MVP to receive some early feedback on the diff process. (Closes #47 )
As I was unsure if it was possible to do this since there isn't any explicit API to create custom diff, I rushed most components to figure out the diff process. There is still plenty of work to do, but hopefully this shows how the diff can look. 
There are some issues due to VSCode not supporting custom diff editors (I think), below is a list.

HexEditor diff 

---

media/editor/dataDisplayContext.tsx
media/editor/hooks.ts
media/editor/state.ts

fix: retain selection state when restoring webview

---

media/editor/state.ts

fix: ctrl+g scroll state being lost when restoring editor

---

media/editor/dataDisplay.tsx
media/editor/findWidget.tsx
media/editor/state.ts
package.json
package.nls.json
shared/protocol.ts
src/copyAs.ts
src/hexEditorProvider.ts

We need a WYSIWYG copy method

---

media/editor/findWidget.tsx

fix: ctrl+f not working with caps lock active

---

package.json

Changed to the position that is right after the  `Compare Selected`. 
Closes: #560

Moved Hex Compare Selected below Compare Selected
